# NumPy for AI/ML – Conceptual & Technical Assessment

## Section A – Conceptual Understanding

###A1. Why are NumPy arrays generally preferred over plain Python lists for numerical computation in AI/ML workloads?

Ans: NumPy arrays are better than Python lists for numerical calculations.They are faster and use memory efficiently.
NumPy also provides many useful functions for mathematical operations.

###A2. Explain vectorization. Why does replacing an explicit Python loop with a vectorized NumPy operation matter with large datasets?



answer:Vectorization means performing operations on an hole NumPy array at once.It avoids using a Python loop for every element.It makes the calculation faster, especially for large datasets.

###A3. For compatible 2D arrays A and B, explain A * B vs A @ B. Describe one neural-network situation for each.

answer:A * B performs multiplication element by element.A @ B performs matrix multiplication.In neural networks, A * B can be used for element-wise operations, while A @ B can be used to calculate the output using weights.

###A4. What is broadcasting in NumPy? State the general rule used to decide whether arrays of different shapes can be combined element-wise.

answer:Broadcasting allows NumPy to perform operations on arrays with different shapes.NumPy compares their shapes from the last dimension.The dimensions must be equal or one of them must be 1.

###A5. Explain flatten() vs ravel(). In a memory-constrained application processing large images, which would you prefer and why?

answer:

flatten() and ravel() are used to convert multi-dimensional array into a 1D array.flatten() creates a copy of the array.
ravel() usually returns a view of the array, so it usesless memory.For large images, I would prefer ravel() because it can save memory.

###A6. For a 2D array, explain axis=0 and axis=1 in an aggregation function such as np.sum() or np.mean(). Illustrate with a small example.

answer:

In a 2D array, axis=0 means the operation is done
column wise.Axis=1 means the operation is done row wise.
For example, np.sum(arr, axis=0) gives the sum of each column.np.sum(arr, axis=1) gives the sum of each row.

###A7. Why is it important to normalize or standardize numerical features before training most ML models? Explain normalization vs standardization.

answer:

Normalization and standardization help bring numerical values to a similar scale.Normalization usually changes values to a range such as 0 to 1.
Standardization changes values based on the mean and standard deviation.This can help ML models work better with features having different scales.

###A8. Why do functions such as np.nanmean() exist? What happens if np.mean() is used directly on data containing NaN?

answer:

np.nanmean() is used to calculate the mean while rejected NaN values.If we use np.mean() on data containing NaN, the result will usually be NaN.So, np.nanmean() is useful when the data has missing values.

###A9. In the ML convention X.shape = (samples, features), explain how this extends to a batch of RGB images. Write the exact shape for 64 RGB images of size 128 × 128.

answer:

for RGB images, we have height, width and 3 color channels.
A batch of images also includes the number of images.
So, 64 RGB images of size 128 × 128 have the shape (64, 128, 128, 3).

###A10. Why is reproducibility important during model development and experimentation? Refer to fixing a random seed with np.random.default_rng(seed).

answer:

Reproducibility means getting the same results when we run the code again.It is important for testing and comparing ML models.Using a fixed seed with np.random.default_rng(seed) gives the same random values each time.

## Section B – Predict the Output

###B1. Predict the exact output and/or resulting shape. Justify in one sentence.
Code:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print((a + b).shape)

expected output:
(3, 3)

->.The arrays are broadcast together, so the result has 3 rows and 3 columns.

###Predict the output and/or shape.

Code:
import numpy as np
x = np.arange(1, 7).reshape(2, 3)
print(x[:, 1])

expected output:
[2 5]

->.The array has 2 rows and 3 columns.x[:, 1] selects all rows and the second column.So the output is [2 5].

###B3. Predict the output and/or shape.

Code:
import numpy as np
arr = np.array([5, 10, 15, 20, 25])
print(arr[arr % 10 == 0])

expected ouput:
[10 20]

->.The condition arr % 10 == 0 selects numbers that are exactly divisible by 10.
So the output is [ 20].

###B4. Predict the output and/or shape.

Code:
import numpy as np
m = np.array([[1, 2],
              [3, 4]])
print(m.T @ m)

expexted output:
[[10 14]
 [14 20]

 ->.m.T changes rows into columns.Then @ performs matrix multiplication.So the resulting matrix is [[10, 14], [14, 20]].

###B5. Predict the output and/or shape.

Code:
import numpy as np
data = np.array([1, 2, np.nan, 4])
print(np.mean(data), np.nanmean(data))

expected output:
 2.3333333333333335

 ->.np.mean() gives nan because the array contains a NaN value.np.nanmean() ignores the NaN value and calculates the mean of 1, 2 and 4.

###B6. Predict the output and/or shape.

Code:
import numpy as np
x = np.array([10, 20, 30])
y = np.where(x > 15, 1, 0)
print(y)

expected output:
[0 1 1]

->.np.where() checks each value.If the value is greater than 15, it gives 1; otherwise, it gives 0.

###B7. Predict the output and/or shape.

Code:
import numpy as np
a = np.zeros((3, 4))
print(a.ndim, a.size)

expected output:
2 , 14

->.ndim tells the number of dimensions of the array.size tells the total number of elements in the array.

###.B8. Predict the output and/or shape.

Code:
import numpy as np
arr = np.arange(1, 13).reshape(3, 4)
print(arr[::-1, ::-1])

expected output:
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]

 ->.[::-1, ::-1] reverses both the rows and the columns.
So the array is reversed from bottom to top and from right to left.

## Section C – Coding / Implementation

###C1. Given a 1D NumPy array of exam scores, use np.where() to produce labels 'P' (score >= 40) or 'F' (score < 40).

code:

import numpy as np
scores = np.array([35, 45, 60, 25, 80])
result = np.where(scores >= 40, 'P', 'F')
print(result)

output:
['F' 'P' 'P' 'F' 'P']

explanation:
np.where() gives P for scores 40 or above and F for scores below 40.

###C2. Write a funct
ion standardize(x) that takes a 1D NumPy array and returns its z-score standardized version using only NumPy.

code:

import numpy as np
x = np.array([10, 20, 30, 40, 50])
result = (x - np.mean(x)) / np.std(x)
print(result)

output:
[-1.41421356 -0.70710678  0.  0.70710678  1.41421356]

explanation:
This function converts the values into standardized values using mean and standard deviation.

###C3. Given two 2D NumPy arrays representing separate batches with the same number of features, combine them using an appropriate NumPy stacking function and print the resulting shape.

code:
 import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.vstack((a, b))
print(result)
print(result.shape)
output:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
explanation:
np.vstack() combines the two arrays row-wise, so the final shape is (4, 2).

###C4. Given X with shape (100, 5), compute column-wise mean and standard deviation and standardize the matrix in one vectorized expression.

code:

import numpy as np
X = np.random.rand(100, 5)
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_standardized = (X - mean) / std
print(X_standardized.shape)

explanation:
axis=0 calculates the mean and standard deviation for each column.The matrix is then standardized using (X - mean) / std.

###C5. Implement y_pred = X @ w + b for a feature matrix X, weight vector w and bias b. Then compute MSE using y_true.

code:

import numpy as np
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])
w = np.array([1, 2])
b = 1
y_true = np.array([6, 9, 12])
y_pred = X @ w + b
mse = np.mean((y_true - y_pred) ** 2)
print(y_pred)
print(mse)

output:
[6 9 12]
0.0

explanation:
X @ w + b calculates the predicted values, and MSE measures the difference between actual and predicted values.


###C6. Using np.random.default_rng() with a fixed seed, generate 10 samples and 3 features from a normal distribution. Print the shape and confirm identical results with the same seed.

code:

import numpy as np
rng1 = np.random.default_rng(10)
a = rng1.normal(size=(10, 3))
rng2 = np.random.default_rng(10)
b = rng2.normal(size=(10, 3))
print(a.shape)
print(np.array_equal(a, b))

output:
(10, 3)
True

explanation:
The same seed generates the same random values, so both arrays are identical.

###C7. Given a grayscale image as a 2D NumPy array with pixel values in [0, 255], normalize the values to [0, 1] using min-max normalization.

code:

import numpy as np
image = np.array([[0, 50, 100], [150, 200, 255]])
normalized = (image - image.min()) / (image.max() - image.min())
print(normalized)

output:
[[0.         0.19607843 0.39215686]
 [0.58823529 0.78431373 1.        ]]

 explanation:
 Min-max normalization changes the pixel values from the range 0–255 to the range 0–1.


###C8. Given 4 RGB images of shape (28, 28, 3), stored as shape (4, 28, 28, 3), compute the average pixel value of each image across height, width and channels. State the axis argument and why.

code:

import numpy as np
images = np.random.rand(4, 28, 28, 3)
average = np.mean(images, axis=(1, 2, 3))
print(average)
print(average.shape)

output:
[0.49 0.50 0.51 0.50]
(4,)

explanation:

axis=(1, 2, 3) calculates the mean across height, width and RGB channels for each image.

## Section D – Applied / Scenario-Based Problems

### D1. Data Preprocessing Pipeline

First, we detect the missing values using np.isnan().
Then, we replace the missing value with the mean of the available values.Finally, we standardize the clean data using mean and standard deviation.

code:

import numpy as np
data = np.array([10, 20, np.nan, 40, 50])
print("Missing values:", np.isnan(data))
mean = np.nanmean(data)
data[np.isnan(data)] = mean
print("Clean data:", data)
standardized = (data - np.mean(data)) / np.std(data)
print("Standardized data:", standardized)

output:
Missing values: [False False  True False False]
Clean data: [10. 20. 30. 40. 50.]
Standardized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

explanation:
The NaN value is replaced with the mean, and the cleaned data is then standardized.

###D2. Image Batch Understanding

Explain, with correct NumPy shapes, how a single RGB image differs from a batch of RGB images.Write code to create a dummy batch of 16 images of size 64 × 64 using random pixel values.Compute the average image of the batch, meaning the element-wise mean across all 16 images.State the shape of your result and explain why.

A single RGB image has shape:(64, 64, 3)
A batch of 16 RGB images has shape:(16, 64, 64, 3)

code:

import numpy as np
images = np.random.rand(16, 64, 64, 3)
average_image = np.mean(images, axis=0)
print(average_image.shape)

output:
(64, 64, 3)
 explanation:
 axis=0 calculates the mean across all 16 images, so the result is one average RGB image with shape (64, 64, 3).

###D3. Debug the Model Code

import numpy as np
X = np.array([[1, 2],[2, 3],[3, 4]])
w = np.array([0.5, 1.0])
b = 2.0
y_pred = X @ w + b
y_true = np.array([10, 20, 30])
mse = np.mean((y_true - y_pred) ** 2)
print(y_pred)
print(mse)

output:
[4.5 5.5 6.5]
60.25

explanation:
The weight vector must have 2 values because X has 2 features.The brackets in the MSE formula are important because the difference must be squared before taking the mean.

## Section E – Bonus / Challenge

###E1. Per-Column Min-Max Normalization

import numpy as np
X = np.array([[10, 100],[20, 200],[30, 300]])
minimum = X.min(axis=0)
maximum = X.max(axis=0)
result = (X - minimum) / (maximum - minimum)
print(result)

output:
[[0. 0.]
[0.5 0.5]
[1. 1.]]

explanation:
Each column is normalized separately to the range 0 to 1.

###E2. Three-Level Score Classification

import numpy as np
scores = np.array([25, 40, 55, 70, 85])
result = np.where(scores < 40, "Fail",np.where(scores <= 70, "Average", "Excellent"))
print(result)

output:

['Fail' 'Average' 'Average' 'Average' 'Excellent']

explanation:
np.where() checks the score and assigns Fail, Average, or Excellent without using if/else or loops.
