In [1]:
pip install numpy


   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 4.6 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/12.6 MB 5.0 MB/s eta 0:00:03
   ------ --------------------------------- 2.1/12.6 MB 4.1 MB/s eta 0:00:03
   --------- ------------------------------ 2.9/12.6 MB 3.9 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.6 MB 4.0 MB/s eta 0:00:03
   -------------- ------------------------- 4.5/12.6 MB 3.8 MB/s eta 0:00:03
   ----------------- ---------------------- 5.5/12.6 MB 3.9 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.6 MB 3.8 MB/s eta 0:00:02
   -------------------- ------------------- 6.3/12.6 MB 3.3 MB/s eta 0:00:02
   -------------------- ------------------- 6.6/12.6 MB 3.3 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.6 MB 3.2 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.6 MB 3.1 MB/s eta 0:00:02
   ---


[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
arr_1d=np.array([1,2,3,4,5])
print(arr_1d)

[1 2 3 4 5]


In [4]:
values_list=[1,2,3,4,5]
values_array=np.array([1,2,3,4,5])
print("list:",values_list)
print("Numpy array:",values_array)
print("Array * 2:",values_array * 2)

list: [1, 2, 3, 4, 5]
Numpy array: [1 2 3 4 5]
Array * 2: [ 2  4  6  8 10]


In [6]:
arr_2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
full = np.full((5,6),7)
print(full)


[[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
#arr.size
#arr.shape
#arr.ndim
print("size:",arr.size)

size: 10


In [39]:
import numpy as np

arr = np.arange(1, 10)

matrix = arr.reshape(3, 3)

cube = np.arange(1, 25).reshape(2, 3, 4)

print("Original:", arr)

print("\n3 x 3:\n", matrix)

print("\n3D shape:", cube.shape)

print(cube)

Original: [1 2 3 4 5 6 7 8 9]

3 x 3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

3D shape: (2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [43]:
matrix=np.array([[1,2,3,4],[5,6,7,8]])
print(matrix)
print("\ntranspose:\n",matrix.T)
print("transpose shape:",matrix.T.shape)
print("\nflatten:",matrix.flatten())

[[1 2 3 4]
 [5 6 7 8]]

transpose:
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]
transpose shape: (4, 2)

flatten: [1 2 3 4 5 6 7 8]
